ltslam:

  # sessions_dir: "/home/ding/mapper_ws/src/lt-mapper/pcdfiles/" # end with / 

  # central_sess_name: "01" # should be same as the directory name of that session
  # query_sess_name: "02" # should be same as the directory name of that session
  
  # save_directory: "/home/ding/mapper_ws/src/lt-mapper/pcdfiles/out/01-02-manyloops/" # end with "/"

  sessions_dir: "/home/ding/backup/dataset/haibo/" # end with / 

  central_sess_name: "lt_lidar_map" # should be same as the directory name of that session
  query_sess_name: "02" # should be same as the directory name of that session
  
  save_directory: "/home/ding/backup/dataset/haibo/out/01-02-manyloops/" # end with "/"

  is_display_debug_msgs: false

  loopFitnessScoreThreshold: 2.0  # 0.7

  kNumSCLoopsUpperBound: 1000 # if you use an enough number, use all the detected loops 
  kNumRSLoopsUpperBound: 10 # if you use an enough number, use all the detected loops 
  RSLoopsThreshold: 10.0 

  numberOfCores: 16 # currently hard-coded in the utility.cpp

